[package]
name = "praeco-jwt-creator"
version = "0.4.1"
edition.workspace = true
description = "JWT generation utility for praeco-rs"
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
jsonwebtoken = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
