[package]
name = "praeco-jwt-creator"
version = "0.4.1"
edition.workspace = true
description = "JWT generation utility for praeco-rs"
license.workspace = true
authors.workspace = true
repository.workspace = true


keywords = ["jwt", "eddsa", "ed25519", "tokens", "cli"]
categories = ["command-line-utilities", "cryptography", "authentication"]

[dependencies]
jsonwebtoken = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
