[package]
name = "praeco-cert-decoder"
version = "0.4.1"
edition.workspace = true
description = "Certificate decoder utility for praeco-rs"
license.workspace = true
authors.workspace = true
repository.workspace = true


keywords = ["x509", "certificates", "san", "decoder", "cli"]
categories = ["command-line-utilities", "cryptography"]

[dependencies]
asn1-rs = { workspace = true, features = ["bigint"] }
pem = { workspace = true }
x509-parser = { workspace = true }
